# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8748b99071916eb24fea81caf8fce33f6d01f1869ea2758e7a6076ca7525406a01e4998e6e72e72c7c10dc846326fe347549c2ec39bfae3b0e55b219811c86b4

test:
  secret_key_base: 5b599509c870d272003c008ce26d8519a44e496b233b1c9c000dee718045cce34522dbf8d8d2933b251d78b2f109097268c68d09f5bbb93a8e7b7a1dc22f0396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
